export interface BhautikDataall {
    scheme_name: string;
    totalpopulation: string;
      alltribalegaav: string; 
    tribalpopulation: string;
    tribalpopulationtkkwari: string;
    totalfamilynumbers: string;
    tribalwholefamilynumbers: string;
    aadhaarcard: string;
    voteridcard: string;
    rationcard: string;
    jobcard: string;
    pmfarmercard: string;
    ayushmancard: string;
    electrificationforfamilies: string;
    elementaryschool: string;
    middleschool: string;
    riverlake: string;
    id: number;
    status: string;
    contact_no: string;
    forestshareholderno: string;
    collectiveforestry: string;
    cfrmplan: string;
    breedstandards: string;
    adivasis: string;
    tribalbenefitnumber: string;
    stepfacilities: string;
    everygharnaalyojana: string;
    healthfacilityis: string;
    generalhealthcheckup: string;
    taluka_name: string;
    village_name: string;
    grampanchayat_name: string;
    sickleanemia: string;
    kindergarten: string;
    mobilefacilities: string;
    mobilemedicalunit: string;
    gotulsocietybuilding: string;
    // rationcard_no: string;
    allroadvillages: string;
    village_distance: string;
    taluka_id: string;
    village_id: string;
    gp_id: string;
    gramPanchayatBuilding: string;
        userId: string;
}
export interface vyaktikDataall {
    id: number,
    scheme_name: string,
    agedata: string,
    castdata: string,
    totalmembersname: string,
    familymembercount: string,
    castcertificate: string,
    aadharcard: string,
    voteridcard: string,
      taluka_name: string;
    village_name: string;
    grampanchayat_name: string;
    rationcardtype: string,
    rationcard_no: string,
    rationcard: string,
    jobcard: string,
    pmfarmercard: string,
    farmercreditcard: string,
    aayushmancard: string,
    headofmember: string,
    pmKisanCard: string,
    ayushmanCard: string,
    housetype: string,
    benefiteofpmhouse: string,
    waterdrink: string,
    hargharnal: string,
    electricity: string,
    hospitalphc: string,
    sanjaygandhi: string,
    contact_no: string,
    studybenefite: string,
    farmeavilebleornot: string,
    studyvanpatta: string,
    sikklacelloffamily: string,
    whichschoolchlid: string,
    anyhaveaashramschool: string,
    lpggas: string,
    bankaccount: string,
    studtatcoop: string,
    pmvimayojna: string,
    praklpkaryalaly: string,
    itarvibhagudan: string,
    niymitaarogya: string,
    status: string,
    taluka_id: string;
    village_id: string;
    gp_id: string;
    userId: string;
    
}

